name: Vercel Repository Dispatch Events

on:
  repository_dispatch:
    types:
      - 'vercel.deployment.success'
      - 'vercel.deployment.error'
      - 'vercel.deployment.canceled'
      - 'vercel.deployment.ignored'
      - 'vercel.deployment.skipped'
      - 'vercel.deployment.pending'
      - 'vercel.deployment.failed'
      - 'vercel.deployment.promoted'
jobs:
  run-e2es:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
     
      - name: Log Github event payload
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Client Payload: ${{ toJson(github.event.client_payload) }}"
     